// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2024/6/7 14:38:43
const configMerger = require("E:/wsy/register/other/WebServer/mind-scrolls/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["E:/wsy/register/other/WebServer/mind-scrolls/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/wsy/register/other/WebServer/mind-scrolls/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/wsy/register/other/WebServer/mind-scrolls/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/wsy/register/other/WebServer/mind-scrolls/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/wsy/register/other/WebServer/mind-scrolls/plugins/**/*.{js,ts,mjs}","E:/wsy/register/other/WebServer/mind-scrolls/composables/**/*.{js,ts,mjs}","E:/wsy/register/other/WebServer/mind-scrolls/utils/**/*.{js,ts,mjs}","E:/wsy/register/other/WebServer/mind-scrolls/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/wsy/register/other/WebServer/mind-scrolls/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/wsy/register/other/WebServer/mind-scrolls/app.config.{js,ts,mjs}"] }));

module.exports = config
